# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpack < Formula
  desc "Tmux Plugin Manager"
  homepage "https://github.com/tmuxpack/tpack"
  version "0.5.1"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.1/tpack_0.5.1_darwin_amd64.tar.gz"
      sha256 "61eb369d51ba7c0c83a98a9a4c2451eeb4084b6c1af7415eee303b0fcf73410a"

      define_method(:install) do
        bin.install "tpack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.1/tpack_0.5.1_darwin_arm64.tar.gz"
      sha256 "375627c100c1b6a8864f20d6e6c4680b8092afb7c2b99217ef820009dea8c527"

      define_method(:install) do
        bin.install "tpack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.1/tpack_0.5.1_linux_amd64.tar.gz"
      sha256 "48ba1cf1e5da47bc75a4cf336ecd9238095bd7ddedc8d7a03f5e71bfe99856cb"
      define_method(:install) do
        bin.install "tpack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.1/tpack_0.5.1_linux_arm64.tar.gz"
      sha256 "26cbee0cdf5965b57955081e19fe2f3316ca998fbefd5f8967c526fbc132b7e5"
      define_method(:install) do
        bin.install "tpack"
      end
    end
  end
end
