# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpack < Formula
  desc "Tmux Plugin Manager"
  homepage "https://github.com/tmuxpack/tpack"
  version "0.7.0"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.7.0/tpack_0.7.0_darwin_amd64.tar.gz"
      sha256 "6172820f038dea6c206bc053fd15354877c7479b263cb3ec11448eb96b2ef74d"

      define_method(:install) do
        bin.install "tpack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.7.0/tpack_0.7.0_darwin_arm64.tar.gz"
      sha256 "81f3bbf8e89f60903ed10806bb7d3c9da70dfe112c2dbba33157003fd8e161e0"

      define_method(:install) do
        bin.install "tpack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.7.0/tpack_0.7.0_linux_amd64.tar.gz"
      sha256 "86f1d01415f604abf1f5b9a0397ef69b81316d672a7e2385204affa9942bbe88"
      define_method(:install) do
        bin.install "tpack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.7.0/tpack_0.7.0_linux_arm64.tar.gz"
      sha256 "92129798be4e4dde5f9d029fa65aa4f51a94d974f7974d11b7306e4a4b947175"
      define_method(:install) do
        bin.install "tpack"
      end
    end
  end
end
