# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpack < Formula
  desc "Tmux Plugin Manager"
  homepage "https://github.com/tmuxpack/tpack"
  version "0.5.2"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.2/tpack_0.5.2_darwin_amd64.tar.gz"
      sha256 "917b3c72c04c93a74cad341e298e98efc68c735b1156158a807d335ef183bc99"

      define_method(:install) do
        bin.install "tpack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.2/tpack_0.5.2_darwin_arm64.tar.gz"
      sha256 "62072c11153acbb02b78961118c2c19ad3ecb29601222efde154e8d93f69936c"

      define_method(:install) do
        bin.install "tpack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.2/tpack_0.5.2_linux_amd64.tar.gz"
      sha256 "70c41280c63b2bfd1896777df6f3876d5960e597ae7d581fa8698636133784ba"
      define_method(:install) do
        bin.install "tpack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmuxpack/tpack/releases/download/v0.5.2/tpack_0.5.2_linux_arm64.tar.gz"
      sha256 "bc8757b561a933b641572ece5fc2781e362ad37899128c0599fee94fbdd69eee"
      define_method(:install) do
        bin.install "tpack"
      end
    end
  end
end
