# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpack" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "1dd93fa91dbcb6b28a7ecef496fd6f110293d51b62f7a20f06991c987f7ac9e6"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "95b41b41ad791b37ffd49181f6b049a0a550c784eaaa75d2dff9e1bbd5ac74ee"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a07c488058282edfc15e127d8077bf4e360cf98ea8b77eb8f396996c73bde04"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6705ee951f76ce93b76558df3488a2a9fa974c823cfd8005b7cd33b0f7525326"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tpack"
  desc "Tmux Plugin Manager"
  homepage "https://github.com/tmuxpack/tpack"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "tpack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tpack"]
    end
  end

  # No zap stanza required

end
