# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpack" do
  version "2.0.4"

  on_macos do
    on_intel do
      sha256 "e5ea897827f23f58ab31a84512378bca98bf1393e9ba638be0473bd6100e272b"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c136618615a66cffb3937eb0dd90d36e3dc8782f108817b6ceb8ff3fad5c36f3"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "337713e472dcc88c26689f5f44d5274715e2ef389cc1f881fbf8137fad7d5b57"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7abe43d2923d203206bcbbec21cb11a59a174e14917f56106b877bf715dbffe3"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tpack"
  desc "Tmux Plugin Manager"
  homepage "https://github.com/tmuxpack/tpack"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "tpack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tpack"]
    end
  end

  # No zap stanza required

end
