# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpack" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "0866195598687b4c4d1a18314dab8462782e17787ef31b03b6f84d0704647dd7"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "94091c3ef8e3202d4558879816de6783b3f7c4c2aa7b7ece545ea37d3ef62bc7"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8490e606f9e8ef2057d1b465cfdac8e84a64b510cecd35a048a85a60c9ce85d0"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8def52fe23507a2f1d4245d046420bb7c963e0b2db7dcfa3d6e79de3e3251c52"
      url "https://github.com/tmuxpack/tpack/releases/download/v#{version}/tpack_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tpack"
  desc "Tmux Plugin Manager"
  homepage "https://github.com/tmuxpack/tpack"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "tpack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tpack"]
    end
  end

  # No zap stanza required

end
